language: android
android:
   components:
   - android-23
   - tools
   - build-tools-23.0.3
   - extra

jdk: oraclejdk7

script:
  - ./gradlew --stacktrace clean build

env:
- GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"